name: 'NocoDB Release'

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      tag:
        description: "Target Tag"
        required: true
      prev_tag:
        description: "Previous Tag"
        required: true
jobs:
  # Close all issues with target tags 'Fixed' & 'Resolved'
  # TODO: add 'Fixed in vX.Y.Z' comment after closing.
  close-fixed-issues:
    needs: release-npm
    uses: ./.github/workflows/release-close-issue.yml
    with:
      issue_label: 'Fixed'
  close-resolved-issues:
    needs: close-fixed-issues
    uses: ./.github/workflows/release-close-issue.yml
    with:
      issue_label: 'Resolved'

  # Build, install, publish frontend and backend to npm
  release-npm:
    uses: ./.github/workflows/release-npm.yml
    with:
      tag: tag

  # Draft Release Note
  release-draft-note:
    needs: close-issues
    uses: ./.github/workflows/release-draft.yml
    with:
      tag: tag
      prev_tag: prev_tag

  # Build docker image and push to docker hub
  release-docker:
    needs: release-draft-note
    uses: ./.github/workflows/release-docker.yml
    with:
      tag: tag

  # Sync changes to develop
  sync-to-develop:
    needs: release-docker
    uses: ./.github/workflows/sync-to-develop.yml