name: "Release : Timely Executables"

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true
  # Triggered by release-nocodb.yml
  workflow_call:
    inputs:
      tag:
        description: "Tag name"
        required: true
        type: string
    secrets:
      NC_GITHUB_TOKEN:
        required: true
jobs:
  build-executables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache pkg modules
        id: cache-pkg
        uses: actions/cache@v3
        env:
          cache-name: cache-pkg
        with:
          # pkg cache files are stored in `~/.pkg-cache`
          path: ~/.pkg-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # for building images for all platforms these librarues
      - name: Install QEMU and ldid
        run: |
          # Install qemu
          sudo apt install qemu binfmt-support qemu-user-static
          # install ldid
          git clone https://github.com/daeken/ldid.git
          cd ./ldid
          ./make.sh
          sudo cp ./ldid /usr/local/bin

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name : Install nocodb, other dependencies and build executables
        run: |
          cd ./scripts/pkg-executable

          # Install nocodb version based on provided tag name
          npm i -E nocodb@$TAG

          # install npm dependendencies
          npm i

          # Copy sqlite binaries
          rsync -rvzhP ./binaries/binding/ ./node_modules/sqlite3/lib/binding/

          # clean up code to optimize size
          npx modclean --patterns="default:*" --ignore="nc-lib-gui-daily/**,dayjs/**,express-status-monitor/**,sqlite3/**" --run

          # build executables
          npm run build

          # Move macOS executables for signing
          mkdir ./mac-dist
          mv ./dist/Noco-macos-arm64 ./mac-dist/
          mv ./dist/Noco-macos-x64 ./mac-dist/

      - name: Upload executables(except mac executables) to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.NC_GITHUB_TOKEN }}
          file: scripts/pkg-executable/dist/**
          tag: ${{ github.event.inputs.tag || inputs.tag }}
          overwrite: true
          file_glob: true

      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.event.inputs.tag || inputs.tag }}
          path: scripts/pkg-executable/mac-dist
          retention-days: 1

  sign-mac-executables:
    runs-on: macos-latest
    needs: build-executables
    steps:

      - uses: actions/download-artifact@master
        with:
          name: ${{ github.event.inputs.tag || inputs.tag }}
          path: scripts/pkg-executable/mac-dist

      - name: Sign macOS executables
        run: |
          /usr/bin/codesign --force -s - ./scripts/pkg-executable/mac-dist/Noco-macos-arm64 -v
          /usr/bin/codesign --force -s - ./scripts/pkg-executable/mac-dist/Noco-macos-x64 -v

      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.event.inputs.tag || inputs.tag }}
          path: scripts/pkg-executable/mac-dist
          retention-days: 1


  publish-mac-executables-and-homebrew:
    needs: sign-mac-executables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: ${{ github.event.inputs.tag || inputs.tag }}
          path: scripts/pkg-executable/mac-dist



      - uses: actions/checkout@v3
        with:
          path: 'homebrew-nocodb'
          token: ${{ secrets.NC_GITHUB_TOKEN }}
          repository: 'nocodb/homebrew-noco'
          fetch-depth: 0

      - name: Compress files and calculate checksum
          run: |
            cp ./mac-dist/Noco-macos-x64 ./mac-dist/noco
            tar -czf ./mac-dist/noco.tar.gz ./mac-dist/noco
            rm ./mac-dist/noco
            echo "::set-output name=CHECKSUM::$(shasum -a 256 ./mac-dist/noco.tar.gz | awk '{print $1}')"
          id: compress



      - name: Upload mac executables to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.NC_GITHUB_TOKEN }}
          file: scripts/pkg-executable/mac-dist/**
          tag: ${{ github.event.inputs.tag || inputs.tag }}
          overwrite: true
          file_glob: true


      - name: Generate Homebrew Formula class and push
        run: |
          FORMULA_CLASS_STR=$(cat << EOF
          class Noco < Formula
            desc "Get Human Readable file size information. - CLI"
            homepage "https://github.com/nocodb/nocodb"
            url "https://github.com/novcodb/nocodb/releases/download/${{ github.event.inputs.tag || inputs.tag }}/noco.tar.gz"
            sha256 "${{ steps.compress.outputs.CHECKSUM }}"
            license "MIT"
            version "${{ github.event.inputs.tag || inputs.tag }}"

            def install
              bin.install "noco"
            end
          end
          EOF
          )

          printf "$FORMULA_CLASS_STR" > homebrew-nocodb/Formula/noco.rb

          cd ./homebrew-nocodb

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git commit ./Formula/noco.rb -m "Automatic publish"
          git push




