# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Unit Tests

on:
  push:
    branches: [ "develop" ]
    paths:
      - "packages/nocodb/**"
  pull_request:
    branches: [ "develop" ]
    paths:
      - "packages/nocodb/**"

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: install dependencies nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: pnpm install --frozen-lockfile
      - name: build nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: pnpm run build:main
      - name: install dependencies nocodb
        working-directory: ./packages/nocodb
        run: pnpm install --frozen-lockfile
      - name: run unit tests
        working-directory: ./packages/nocodb
        run: pnpm run unit-test